name: Deploy celulares api

on:
  push:
    branches: ["master"]

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Crear archivo .env
        run: |
          echo 'DEV_DATABASE_URL=${{ secrets.PG_CONN }}' >> .env
          cat .env

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/pg-restapi-celulares:${{ github.sha }} .

      - name: Show Docker images
        run: docker images

      - name: Login to DockerHub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/pg-restapi-celulares:${{ github.sha }}
